import { useState } from "react";
import {
  League,
  SimCBB,
  SimCFB,
  SimCHL,
  SimCollegeBaseball,
  SimMLB,
  SimNBA,
  SimNFL,
  SimPHL,
} from "../../_constants/constants";
import routes from "../../_constants/routes";
import { useNavigate } from "react-router-dom";
import { useDeepLink } from "../../context/DeepLinkContext";

// ✅ Types
interface DropdownItem {
  label: string;
  league: League;
  isRoute: boolean;
  route: string;
  toggle: () => void;
  click?: () => void;
}

export const useSideMenu = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const navigate = useNavigate();
  const { goToTeamPage } = useDeepLink();

  const toggleMenu = () => setIsOpen((prev) => !prev);
  const toggleDropdown = () => setIsDropdownOpen((prev) => !prev);
  const dropdowns: Record<string, DropdownItem[]> = {
    SimCFB: [
      {
        label: "Team Profile",
        isRoute: true,
        route: routes.CFB_TEAMPROFILE,
        league: SimCFB,
        toggle: () => toggleMenu(),
      },
      {
        label: "Roster",
        isRoute: true,
        route: routes.CFB_TEAM,
        league: SimCFB,
        toggle: () => toggleMenu(),
        click: () => goToTeamPage(SimCFB),
      },
      {
        label: "Gameplan",
        isRoute: true,
        route: routes.CFB_GAMEPLAN,
        league: SimCFB,
        click: () => navigate(routes.CFB_GAMEPLAN),
        toggle: () => toggleMenu(),
      },
      {
        label: "Recruiting",
        isRoute: true,
        route: routes.CFB_RECRUITING,
        league: SimCFB,
        click: () => navigate(routes.CFB_RECRUITING),
        toggle: () => toggleMenu(),
      },
      {
        label: "Statistics",
        isRoute: true,
        route: routes.CFB_STATS,
        league: SimCFB,
        click: () => navigate(routes.CFB_STATS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Schedule",
        isRoute: true,
        route: routes.CFB_SCHEDULE,
        league: SimCFB,
        toggle: () => toggleMenu(),
      },
      {
        label: "Transfer Portal",
        isRoute: true,
        route: routes.CFB_TRANSFER,
        league: SimCFB,
        toggle: () => toggleMenu(),
      },
    ],
    SimNFL: [
      {
        label: "Team",
        isRoute: true,
        route: routes.NFL_TEAM,
        league: SimNFL,
        click: () => goToTeamPage(SimNFL),
        toggle: () => toggleMenu(),
      },
      {
        label: "Gameplan",
        isRoute: true,
        route: routes.NFL_GAMEPLAN,
        league: SimNFL,
        click: () => navigate(routes.NFL_GAMEPLAN),
        toggle: () => toggleMenu(),
      },
      {
        label: "Free Agency",
        isRoute: true,
        route: routes.NFL_FREE_AGENCY,
        league: SimNFL,
        toggle: () => toggleMenu(),
      },
      {
        label: "Statistics",
        isRoute: true,
        route: routes.NFL_STATS,
        league: SimNFL,
        click: () => navigate(routes.NFL_STATS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Schedule",
        isRoute: true,
        route: routes.NFL_SCHEDULE,
        league: SimNFL,
        toggle: () => toggleMenu(),
      },
      {
        label: "Draft Page",
        isRoute: true,
        route: routes.NFL_DRAFT_ROOM,
        league: SimNFL,
        click: () => navigate(routes.NFL_DRAFT_ROOM),
        toggle: () => toggleMenu(),
      },
    ],
    SimCBB: [
      {
        label: "Team",
        isRoute: true,
        route: routes.CBB_TEAM,
        league: SimCBB,
        click: () => goToTeamPage(SimCBB),
        toggle: () => toggleMenu(),
      },
      {
        label: "Gameplan",
        isRoute: true,
        route: "",
        league: SimCBB,
        toggle: () => toggleMenu(),
      },
      {
        label: "Recruiting",
        isRoute: true,
        route: routes.CBB_RECRUITING,
        league: SimCBB,
        click: () => navigate(routes.CBB_RECRUITING),
        toggle: () => toggleMenu(),
      },
      {
        label: "Statistics",
        isRoute: true,
        route: routes.CBB_STATS,
        league: SimCBB,
        click: () => navigate(routes.CBB_STATS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Schedule",
        isRoute: true,
        route: routes.CBB_SCHEDULE,
        league: SimCBB,
        click: () => navigate(routes.CBB_SCHEDULE),
        toggle: () => toggleMenu(),
      },
      {
        label: "Transfer Portal",
        isRoute: true,
        route: routes.CBB_TRANSFER,
        league: SimCBB,
        toggle: () => toggleMenu(),
      },
    ],
    SimNBA: [
      {
        label: "Team",
        isRoute: true,
        route: routes.NBA_TEAM,
        league: SimNBA,
        click: () => goToTeamPage(SimNBA),
        toggle: () => toggleMenu(),
      },
      {
        label: "Gameplan",
        isRoute: true,
        route: "",
        league: SimNBA,
        toggle: () => toggleMenu(),
      },
      {
        label: "Free Agency",
        isRoute: true,
        route: "",
        league: SimNBA,
        toggle: () => toggleMenu(),
      },
      {
        label: "Statistics",
        isRoute: true,
        route: routes.NBA_STATS,
        league: SimNBA,
        click: () => navigate(routes.NBA_STATS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Schedule",
        isRoute: true,
        route: "",
        league: SimNBA,
        click: () => navigate(routes.NBA_SCHEDULE),
        toggle: () => toggleMenu(),
      },
      {
        label: "Draft Page",
        isRoute: true,
        route: "",
        league: SimNBA,
        toggle: () => toggleMenu(),
      },
    ],
    SimCHL: [
      {
        label: "Team",
        isRoute: true,
        route: routes.CHL_TEAM,
        league: SimCHL,
        click: () => goToTeamPage(SimCHL),
        toggle: () => toggleMenu(),
      },
      {
        label: "Lineup",
        isRoute: true,
        route: routes.CHL_GAMEPLAN,
        league: SimCHL,
        click: () => navigate(routes.CHL_GAMEPLAN),
        toggle: () => toggleMenu(),
      },
      {
        label: "Recruiting",
        isRoute: true,
        route: routes.CHL_RECRUITING,
        league: SimCHL,
        click: () => navigate(routes.CHL_RECRUITING),
        toggle: () => toggleMenu(),
      },
      {
        label: "Schedule",
        isRoute: true,
        route: routes.CHL_SCHEDULE,
        league: SimCHL,
        toggle: () => toggleMenu(),
      },
      {
        label: "Statistics",
        isRoute: true,
        route: routes.CHL_STATS,
        league: SimCHL,
        click: () => navigate(routes.CHL_STATS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Transfer Portal",
        isRoute: true,
        route: routes.CHL_TRANSFER,
        league: SimCHL,
        click: () => navigate(routes.CHL_TRANSFER),
        toggle: () => toggleMenu(),
      },
    ],
    SimPHL: [
      {
        label: "Team",
        isRoute: true,
        route: routes.PHL_TEAM,
        league: SimPHL,
        click: () => goToTeamPage(SimPHL),
        toggle: () => toggleMenu(),
      },
      {
        label: "Lineup",
        isRoute: true,
        route: routes.PHL_GAMEPLAN,
        league: SimPHL,
        click: () => navigate(routes.PHL_GAMEPLAN),
        toggle: () => toggleMenu(),
      },
      {
        label: "Free Agency",
        isRoute: true,
        route: routes.PHL_FREE_AGENCY,
        league: SimPHL,
        click: () => navigate(routes.PHL_FREE_AGENCY),
        toggle: () => toggleMenu(),
      },
      {
        label: "Schedule",
        isRoute: true,
        route: routes.PHL_SCHEDULE,
        league: SimPHL,
        toggle: () => toggleMenu(),
      },
      {
        label: "Statistics",
        isRoute: true,
        route: routes.PHL_STATS,
        league: SimPHL,
        click: () => navigate(routes.PHL_STATS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Draft Page",
        isRoute: true,
        route: routes.PHL_DRAFT_ROOM,
        league: SimPHL,
        toggle: () => toggleMenu(),
      },
    ],
    SimCollegeBaseball: [
      {
        label: "Team",
        isRoute: true,
        route: routes.COLLEGE_BASEBALL_TEAM,
        league: SimCollegeBaseball,
        toggle: () => toggleMenu(),
      },
      {
        label: "Roster Breakdown",
        isRoute: true,
        route: routes.COLLEGE_BASEBALL_FINANCIALS,
        league: SimCollegeBaseball,
        click: () => navigate(routes.COLLEGE_BASEBALL_FINANCIALS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Gameplan",
        isRoute: true,
        route: routes.COLLEGE_BASEBALL_GAMEPLAN,
        league: SimCollegeBaseball,
        click: () => navigate(routes.COLLEGE_BASEBALL_GAMEPLAN),
        toggle: () => toggleMenu(),
      },
      {
        label: "Recruiting",
        isRoute: true,
        route: routes.COLLEGE_BASEBALL_RECRUITING,
        league: SimCollegeBaseball,
        click: () => navigate(routes.COLLEGE_BASEBALL_RECRUITING),
        toggle: () => toggleMenu(),
      },
      {
        label: "Schedule",
        isRoute: true,
        route: routes.COLLEGE_BASEBALL_SCHEDULE,
        league: SimCollegeBaseball,
        click: () => navigate(routes.COLLEGE_BASEBALL_SCHEDULE),
        toggle: () => toggleMenu(),
      },
      {
        label: "Statistics",
        isRoute: true,
        route: routes.COLLEGE_BASEBALL_STATS,
        league: SimCollegeBaseball,
        click: () => navigate(routes.COLLEGE_BASEBALL_STATS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Injuries",
        isRoute: true,
        route: routes.COLLEGE_BASEBALL_INJURIES,
        league: SimCollegeBaseball,
        click: () => navigate(routes.COLLEGE_BASEBALL_INJURIES),
        toggle: () => toggleMenu(),
      },
      {
        label: "Postseason",
        isRoute: true,
        route: routes.COLLEGE_BASEBALL_PLAYOFFS,
        league: SimCollegeBaseball,
        click: () => navigate(routes.COLLEGE_BASEBALL_PLAYOFFS),
        toggle: () => toggleMenu(),
      },
    ],
    SimMLB: [
      {
        label: "Team",
        isRoute: true,
        route: routes.MLB_TEAM,
        league: SimMLB,
        toggle: () => toggleMenu(),
      },
      {
        label: "Financials",
        isRoute: true,
        route: routes.MLB_FINANCIALS,
        league: SimMLB,
        click: () => navigate(routes.MLB_FINANCIALS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Gameplan",
        isRoute: true,
        route: routes.MLB_GAMEPLAN,
        league: SimMLB,
        click: () => navigate(routes.MLB_GAMEPLAN),
        toggle: () => toggleMenu(),
      },
      // {
      //   label: "INTAM Scouting",
      //   isRoute: true,
      //   route: routes.MLB_INTAM_SCOUTING,
      //   league: SimMLB,
      //   click: () => navigate(routes.MLB_INTAM_SCOUTING),
      //   toggle: () => toggleMenu(),
      // },
      {
        label: "Free Agency",
        isRoute: true,
        route: routes.MLB_FREE_AGENCY,
        league: SimMLB,
        click: () => navigate(routes.MLB_FREE_AGENCY),
        toggle: () => toggleMenu(),
      },
      // {
      //   label: "Trades",
      //   isRoute: true,
      //   route: routes.MLB_TRADES,
      //   league: SimMLB,
      //   click: () => navigate(routes.MLB_TRADES),
      //   toggle: () => toggleMenu(),
      // },
      {
        label: "Schedule",
        isRoute: true,
        route: routes.MLB_SCHEDULE,
        league: SimMLB,
        click: () => navigate(routes.MLB_SCHEDULE),
        toggle: () => toggleMenu(),
      },
      {
        label: "Statistics",
        isRoute: true,
        route: routes.MLB_STATS,
        league: SimMLB,
        click: () => navigate(routes.MLB_STATS),
        toggle: () => toggleMenu(),
      },
      {
        label: "Injuries",
        isRoute: true,
        route: routes.MLB_INJURIES,
        league: SimMLB,
        click: () => navigate(routes.MLB_INJURIES),
        toggle: () => toggleMenu(),
      },
      {
        label: "Playoffs",
        isRoute: true,
        route: routes.MLB_PLAYOFFS,
        league: SimMLB,
        click: () => navigate(routes.MLB_PLAYOFFS),
        toggle: () => toggleMenu(),
      },
      {
        label: "All-Star Game",
        isRoute: true,
        route: routes.MLB_ALLSTAR,
        league: SimMLB,
        click: () => navigate(routes.MLB_ALLSTAR),
        toggle: () => toggleMenu(),
      },
      // {
      //   label: "World Baseball Classic",
      //   isRoute: true,
      //   route: routes.MLB_WBC,
      //   league: SimMLB,
      //   click: () => navigate(routes.MLB_WBC),
      //   toggle: () => toggleMenu(),
      // },
      // {
      //   label: "Draft Room",
      //   isRoute: true,
      //   route: routes.MLB_DRAFT_ROOM,
      //   league: SimMLB,
      //   click: () => navigate(routes.MLB_DRAFT_ROOM),
      //   toggle: () => toggleMenu(),
      // },
    ],
  };

  return {
    toggleMenu,
    toggleDropdown,
    dropdowns,
    isOpen,
    isDropdownOpen,
  };
};
